sudo: false
language: node_js
node_js:
  - '6'
cache:
  directories:
    - node_modules
before_install:
  - npm -g install npm@latest
  - npm install -g dredd@4.5.0
install:
  - npm install --no-optional
before_script:
  - dredd
